#@url_base = https://0123456789.execute-api.us-east-1.amazonaws.com
#@url_base = http://localhost:8001/
@url_base = http://3.86.151.171
### Start a new chat
POST {{url_base}}/chats/
Content-Type: application/json

### Continue an existing chat with text query
POST {{url_base}}/chats/YyX3cKGhw6oaajqRS5ABHn/continue
Content-Type: application/json

{
  "query":"when was the college of engineering in the University of Notre Dame established?"
}

### Continue an existing chat with text query
POST {{url_base}}/chats/XeTrppZ5CYsi6Tr3JaNV23/continue-with-voice/
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="query"

test
--boundary
Content-Disposition: form-data; name="voice_file"; filename="test.m4a"
Content-Type: audio/m4a

< ./test.m4a
--boundary--

