#@url_base = http://localhost:8001/
@url_base = http://52.90.91.186
### Start a new chat
POST {{url_base}}/chats/
Content-Type: application/json

### Continue an existing chat with text query
POST {{url_base}}/chats/bDcrzUH35JRDTTfRfqeTFf/continue
Content-Type: application/json

{
  "query":"What is my name?"
}

### Continue an existing chat with text query
POST {{url_base}}/chats/XoyTVZ8Yb7W9iMSvPWLrXG/continue-with-voice
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="query"

test
--boundary
Content-Disposition: form-data; name="voice_file"; filename="test.m4a"
Content-Type: audio/m4a

< ./audio_file.m4a
--boundary--

